version: '3.7'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=vaccine-ms
    volumes:
      - ./data:/var/lib/mysql